### ISSUE TITLE
Software freezes when using the Filter function

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1606]
When using the Filter edit box functionality in the data panel, I have encountered that when having a relative large number of items (255), the software freezes easily and is prompt to crashing.

<img width="509" height="453" alt="Image" src="https://github.com/user-attachments/assets/462d4748-c88f-4265-aeb6-d30f414ebd19" />

**Comment by Ion-e** [comment]
This seems now fixed, it must have been fixed by some other changes. Closing and pinging @cmeyer 
Thanks.

**Comment by cmeyer** [comment]
This is a different issue, better now, but still present. I'd like to keep this open - I have a PR forthcoming in the day or so.

**Comment by cmeyer** [comment]
- #1967
